FROM registry.access.redhat.com/ubi9/go-toolset:9.8-1787080706@sha256:71e89a1a51ab32cc30634d89ee4dc8ea40ad9991057fa1eae3b1af32bc7db73f AS toolchain

# Run this with docker build --build_arg $(go env GOPROXY) to override the goproxy
ARG goproxy=https://proxy.golang.org
ENV GOPROXY=$goproxy

FROM toolchain AS builder

USER 0
WORKDIR /workspace

ENV GOFLAGS="-buildvcs=false"

ARG MCE_VERSION=dev
ARG GIT_COMMIT=unknown

COPY ./ ./

# Cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN  --mount=type=cache,target=/root/.local/share/golang \
     --mount=type=cache,target=/go/pkg/mod \
     go mod download

# Build
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.local/share/golang \
    SHORT_COMMIT=$(echo "${GIT_COMMIT}" | cut -c1-7) && \
    CGO_ENABLED=1 GOOS=linux GOARCH=${ARCH} \
    go build -ldflags "-X 'github.com/Azure/azure-service-operator/v2/internal/version.BuildVersion=${MCE_VERSION}-${SHORT_COMMIT}'" \
    -o ./aso-controller ./cmd/controller/

# Copy the aso-controller into a thin image
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.8-1786380870@sha256:7c372902c8d211db2d25c8277ba534a73b92742a334874dced829a63b0f21221
COPY --from=builder /workspace/aso-controller /aso-controller
COPY stolostron/crds ./crds
USER 65532:65532
ENTRYPOINT ["/aso-controller"]
