FROM registry.access.redhat.com/ubi9/go-toolset:9.8-1787774815@sha256:1a755651ffe1a438f137418d183f18ebad527ec929206c17804f93490a97869e AS toolchain

# Run this with docker build --build_arg $(go env GOPROXY) to override the goproxy
ARG goproxy=https://proxy.golang.org
ENV GOPROXY=$goproxy

FROM toolchain AS builder

USER 0
WORKDIR /workspace

ENV GOFLAGS="-buildvcs=false"

ARG MCE_VERSION=dev
ARG GIT_COMMIT=unknown

COPY ./ ./

# Cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN  --mount=type=cache,target=/root/.local/share/golang \
     --mount=type=cache,target=/go/pkg/mod \
     go mod download

# Build
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.local/share/golang \
    SHORT_COMMIT=$(echo "${GIT_COMMIT}" | cut -c1-7) && \
    CGO_ENABLED=1 GOOS=linux GOARCH=${ARCH} \
    go build -ldflags "-X 'github.com/Azure/azure-service-operator/v2/internal/version.BuildVersion=${MCE_VERSION}-${SHORT_COMMIT}'" \
    -o ./aso-controller ./cmd/controller/

# Copy the aso-controller into a thin image
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.8-1787647261@sha256:580752f96d36c4132bffd30f9c34865bf4bd87f6aa161c969d117f21732e50f7
COPY --from=builder /workspace/aso-controller /aso-controller
COPY stolostron/crds ./crds
USER 65532:65532
ENTRYPOINT ["/aso-controller"]
