/*
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
*/

// Code generated by azure-service-operator-codegen. DO NOT EDIT.

// Package v1api20260901preview contains API Schema definitions for the redhatopenshift v1api20260901preview API group
// +groupName=redhatopenshift.azure.com
package v1api20260901preview
