// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package customizations

import (
	v20251223p "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20251223preview"
	v20251223ps "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20251223preview/storage"
	v20260901p "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20260901preview"
	v20260901ps "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20260901preview/storage"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
)

type HcpOpenShiftClusterExtension struct {
}

// GetExtendedResources Returns the KubernetesResource slice for Resource versions
func (extension *HcpOpenShiftClusterExtension) GetExtendedResources() []genruntime.KubernetesResource {
	return []genruntime.KubernetesResource{
		&v20251223p.HcpOpenShiftCluster{},
		&v20251223ps.HcpOpenShiftCluster{},
		&v20260901p.HcpOpenShiftCluster{},
		&v20260901ps.HcpOpenShiftCluster{}}
}
