// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package customizations

import (
	v20240610p "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20240610preview"
	v20240610ps "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20240610preview/storage"
	v20251223p "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20251223preview"
	v20251223ps "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20251223preview/storage"
	v20260630p "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20260630preview"
	v20260630ps "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20260630preview/storage"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
)

type HcpOpenShiftClustersNodePoolExtension struct {
}

// GetExtendedResources Returns the KubernetesResource slice for Resource versions
func (extension *HcpOpenShiftClustersNodePoolExtension) GetExtendedResources() []genruntime.KubernetesResource {
	return []genruntime.KubernetesResource{
		&v20240610p.HcpOpenShiftClustersNodePool{},
		&v20240610ps.HcpOpenShiftClustersNodePool{},
		&v20251223p.HcpOpenShiftClustersNodePool{},
		&v20251223ps.HcpOpenShiftClustersNodePool{},
		&v20260630p.HcpOpenShiftClustersNodePool{},
		&v20260630ps.HcpOpenShiftClustersNodePool{}}
}
