// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package customizations

import (
	v20251223p "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20251223preview"
	v20251223ps "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20251223preview/storage"
	v20260630p "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20260630preview"
	v20260630ps "github.com/Azure/azure-service-operator/v2/api/redhatopenshift/v1api20260630preview/storage"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
)

type HcpOpenShiftClustersExternalAuthExtension struct {
}

// GetExtendedResources Returns the KubernetesResource slice for Resource versions
func (extension *HcpOpenShiftClustersExternalAuthExtension) GetExtendedResources() []genruntime.KubernetesResource {
	return []genruntime.KubernetesResource{
		&v20251223p.HcpOpenShiftClustersExternalAuth{},
		&v20251223ps.HcpOpenShiftClustersExternalAuth{},
		&v20260630p.HcpOpenShiftClustersExternalAuth{},
		&v20260630ps.HcpOpenShiftClustersExternalAuth{}}
}
