name: Create new Stolostron release

on:
  # run when a release is published,
  # which creates a new tag
  push:
    tags:
      - v2*

permissions: {}

jobs:
  build-and-push:
    uses: ./.github/workflows/build-release-artifacts.yml
    with:
      upload: true
      tag: ${{ github.ref }}
    secrets: inherit
